### ISSUE TITLE
What is the fetch program used in the first image in readme?

### ISSUE THREAD

**Issue by SisyphusIsntHappy** [BachoSeven/dotfiles#2]
The title itself.

**Comment by BachoSeven** [comment]
Hi! That script is present in this repo as `.local/bin/colors/fetch`.

It's not mine though, the original author's version can be found [here](http://code.xero.nu/dotfiles/master/7f93a82f401f7170ce533bfd143513450030f2a3/blob/70e6a1d66dc7b220cac9bd2f3663802bdafd7382).
