### ISSUE TITLE
What is the fetch tool used in the screenshots?

### ISSUE THREAD

**Issue by yogeshdofficial** [BachoSeven/dotfiles#3]
in [this](https://camo.githubusercontent.com/9e6838a491ace26116c13c7715bfd082f44aadd501303a4ffcd6060d447d68ae/68747470733a2f2f692e696d6775722e636f6d2f4952364f6378412e706e67) one and [this](https://camo.githubusercontent.com/c16206ef358d6a5caf8b472d9b7ff2c6a84ff4bfa34bb373d0c468699417f446/68747470733a2f2f692e696d6775722e636f6d2f757954786f6e6e2e6a7067)

**Comment by BachoSeven** [comment]
The first one is a custom script found in this repository, under `.local/bin/colors/fetch`

The secondo one is just [pfetch](https://github.com/dylanaraps/pfetch)
